# 1 工作流名称
name: CI

# 2 工作流执行名称
# run-name: ${{ github.actor }} is update repo, start building...

# 3 触发器
on:
  # push 推送
  push:
    branches: ["main"]
  
# 4 设置权限（文件是可以被读写修改的）
permissions:
  contents: write

# 工作1
jobs:
  # 任务名称
  build:
    # 执行平台
    runs-on: ubuntu-latest
 
    # 任务步骤
    steps:
      # 1 将代码仓库的内容拉取（或称为检出）到工作目录中，以便在下面的工作流程中使用
      - name: Check out the repository to the runner
        uses: actions/checkout@v4 
      
